version: 2

models:
  - name: cc_sales
    description:

    columns:
      - name: product_id
        tests:
          - unique
          - not_null
          
  - name: cc_stock
    description: This table has basic information about the catalog of products

    columns:
      - name: model
        tests:
          - unique
          - not_null